name: CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
  lint:
    name: Source code formatting & spellcheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 16
        uses: dafnik/setup-node-pnpm@v1
        with:
          node: 16
          install: true

      - name: Check formatting with Prettier
        run: pnpm format:check

      - name: Spellcheck (entire repository)
        run: pnpm spellcheck

  typecheck:
    name: Typecheck & linting
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 16
        uses: dafnik/setup-node-pnpm@v1
        with:
          node: 16
          install: true

      - name: Lint with ESLint
        run: pnpm lint

      - name: Check Typescript
        run: pnpm typecheck
